# Generated by Django 5.2.10 on 2026-03-18 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer'),
        ('memory', '0004_improve_hnsw_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='accounts.customer'),
        ),
    ]
