# Generated by Django 5.2.10 on 2026-03-19 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer'),
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to='accounts.customer'),
        ),
    ]
