# Generated by Django 5.2.10 on 2026-03-22 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_github_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('service', models.CharField(choices=[('github', 'github'), ('anthropic', 'anthropic'), ('gemini', 'gemini')], max_length=64)),
                ('secret_arn', models.CharField(max_length=512)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='accounts.customer')),
            ],
            options={
                'unique_together': {('customer', 'service')},
            },
        ),
    ]
