"""
Django settings for mrvn project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import logging
import os
from pathlib import Path

from django.conf.locale.en import formats as en_formats
from django.conf.locale.ja import formats as ja_formats
from django.utils.translation import gettext_lazy as _


def strtobool(val: str | int | bool) -> bool:
    """stringをboolに変換"""
    if isinstance(val, bool):
        return val
    if isinstance(val, str):
        return val.lower() in ["true", "1", "t", "y", "yes"]
    if isinstance(val, int):
        return val == 1
    return bool(val)


# reduce logging output from noisy packages
logging.getLogger("requests").setLevel(logging.WARNING)
logging.getLogger("urllib3").setLevel(logging.WARNING)  # ISO 8601, ex: 2008-01-02T10:30:00.000123+02:00
# NOTE: Will not show timezone offset if datetime object is "naive"
ja_formats.DATETIME_FORMAT = "c"
en_formats.DATETIME_FORMAT = "c"


BASE_DIR = Path(__file__).resolve().parent.parent.absolute()

SITE_HEADER = "REPLACE_ME SITE_HEADER"
SITE_TITLE = "REPLACE_ME SITE_TITLE"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

DEFAULT_IS_LOCAL_DEVELOPMENT = "False"
IS_LOCAL_DEVELOPMENT = bool(strtobool(os.getenv("IS_LOCAL_DEVELOPMENT", DEFAULT_IS_LOCAL_DEVELOPMENT)))

USE_TIMED_TESTRUNNER = strtobool(os.getenv("USE_TIMED_TESTRUNNER", "False"))
if USE_TIMED_TESTRUNNER:
    TEST_RUNNER = "commons.tests.runners.TimedTestRunner"

# For CircleCI to generate JUnit XML test reports and optimize test running time
USE_XML_TESTRUNNER = strtobool(os.getenv("USE_XML_TESTRUNNER", "False"))
if not USE_TIMED_TESTRUNNER and USE_XML_TESTRUNNER:
    TEST_RUNNER = "commons.tests.runners.XMLTestRunnerForCI"
    TEST_OUTPUT_DIR = "test-reports"
    TEST_OUTPUT_FILE_NAME = "results.xml"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "&37^bx2j^ji^mx3v)v0z91zs%^oy=ul!16_-gcd^mrvn"  # noqa: S105

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(strtobool(os.getenv("DEBUG", "False")))

ALLOWED_HOSTS = ["*"]  # TODO: Update this to your domain name  # noqa: TD002

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "psqlextra",
    "rest_framework",
    # Local apps
    "commons",
    "accounts",
    "agents",
    "channels",
    "memory",
    "autoreply",
]

# Django REST Framework settings
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}

AUTH_USER_MODEL = "accounts.CustomUser"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "mrvn.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "commons.context_processors.global_view_additional_context",  # PROVIDES settings.URL_PREFIX to context
            ],
        },
    },
]


WSGI_APPLICATION = "mrvn.wsgi.application"


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "psqlextra.backend",  # Required for partitioning
        "NAME": os.getenv("DB_NAME", "mrvn"),
        "USER": os.getenv("DB_USER", "postgres"),
        "PASSWORD": os.getenv("DB_PASS", "mysecretpassword"),
        "HOST": os.getenv("DB_HOST", "127.0.0.1"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}

# Partitioning manager for psqlextra
PSQLEXTRA_PARTITIONING_MANAGER = "memory.partitioning.manager"


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = "ja"
LANGUAGES = [
    ("ja", _("Japanese")),
    ("en", _("English")),
]

TIME_ZONE = "Asia/Tokyo"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

DEFAULT_URL_PREFIX = ""
URL_PREFIX = os.getenv("DJANGO_URL_PREFIX", DEFAULT_URL_PREFIX)
if URL_PREFIX and not URL_PREFIX.startswith("/"):
    URL_PREFIX = f"/{URL_PREFIX}"
STATIC_URL = f"{URL_PREFIX}/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

WHITENOISE_STATIC_PREFIX = "/static/"
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
STATICFILES_DIRS = []


DJANGO_LOG_LEVEL = os.getenv("DJANGO_LOG_LEVEL", "INFO")
DJANGO_CORE_LOG_LEVEL = os.getenv("DJANGO_CORE_LOG_LEVEL", "INFO")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "{asctime} [{levelname:5}] ({name}) {funcName}: {message}",
            "style": "{",
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": DJANGO_CORE_LOG_LEVEL,  # Change to DEBUG to see db queries
        },
        "accounts": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": True,
        },
        "commons": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": True,
        },
        "agents": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": True,
        },
        "channels": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": True,
        },
        "memory": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": True,
        },
        "autoreply": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": True,
        },
    },
}

AWS_REGION = os.getenv("AWS_DEFAULT_REGION", "ap-northeast-1")

# GitHub API token for reading READMEs (optional — unauthenticated calls are rate-limited)
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN", "")
AWS_DEFAULT_REGION = AWS_REGION

# CSRF Settings
# https://docs.djangoproject.com/en/2.2/ref/settings/#std:setting-CSRF_COOKIE_HTTPONLY
CSRF_COOKIE_SECURE = False
DEFAULT_CSRF_USE_SESSIONS = "True"
CSRF_USE_SESSIONS = bool(strtobool(os.getenv("DJANGO_CSRF_USE_SESSIONS", DEFAULT_CSRF_USE_SESSIONS)))


AUTHENTICATION_BACKENDS = ("django.contrib.auth.backends.ModelBackend",)

# LLM Provider Configuration
# Default rate limits per provider (requests per minute)
LLM_PROVIDER_DEFAULTS = {
    "anthropic": {
        "default_rpm": 60,
        "default_model": "claude-sonnet-4-20250514",
    },
    "gemini": {
        "default_rpm": 60,
        "default_model": "gemini-2.0-flash",
    },
    "ollama": {
        "default_rpm": 0,  # No limit for local
        "default_model": "llama3.2",
        "default_base_url": "http://localhost:11434",
    },
    "vllm": {
        "default_rpm": 0,  # No limit for local
        "default_model": "meta-llama/Llama-3.2-8B",
        "default_base_url": "http://localhost:8000/v1",
    },
}

# Global rate limit settings
RATE_LIMIT_ENABLED = bool(strtobool(os.getenv("RATE_LIMIT_ENABLED", "True")))
RATE_LIMIT_DEFAULT_RPM = int(os.getenv("RATE_LIMIT_DEFAULT_RPM", "60"))

# Default LLM models (configurable via environment variables)
DEFAULT_ANTHROPIC_MODEL = os.getenv("DEFAULT_ANTHROPIC_MODEL", "claude-sonnet-4-20250514")
DEFAULT_GEMINI_MODEL = os.getenv("DEFAULT_GEMINI_MODEL", "gemini-2.0-flash")
DEFAULT_OPENAI_MODEL = os.getenv("DEFAULT_OPENAI_MODEL", "gpt-4o")
DEFAULT_OLLAMA_MODEL = os.getenv("DEFAULT_OLLAMA_MODEL", "llama3.2")
DEFAULT_OLLAMA_BASE_URL = os.getenv("DEFAULT_OLLAMA_BASE_URL", "http://localhost:11434")
