# Generated by Django 5.2.10 on 2026-03-18 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer'),
        ('agents', '0005_improve_hnsw_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='accounts.customer'),
        ),
    ]
