# Generated by Django 5.2.10 on 2026-03-23 22:54

import commons.functions
import commons.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_customer_github_token'),
        ('agents', '0007_project_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskEnvelope',
            fields=[
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('id', commons.models.UUID7Field(default=commons.functions.uuidv7, editable=False, primary_key=True, serialize=False)),
                ('issue_url', models.CharField(max_length=512)),
                ('action', models.CharField(max_length=64)),
                ('agent_profile', models.CharField(max_length=64)),
                ('context_s3_prefix', models.CharField(max_length=512)),
                ('duration_hint_seconds', models.IntegerField(default=3600)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('dispatched', 'Dispatched'), ('complete', 'Complete'), ('failed', 'Failed')], default='queued', max_length=32)),
                ('sqs_message_id', models.CharField(max_length=255, unique=True)),
                ('dispatch_result', models.JSONField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_envelopes', to='accounts.customer')),
                ('project_context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_envelopes', to='agents.projectcontext')),
            ],
            options={
                'ordering': ['-created_datetime'],
            },
        ),
    ]
